# from https://github.com/actions-rs/example
on: [push, pull_request]

name: Build

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  gauge-tests:
    name: ree-to-ree tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: npm install wasm-pack
      - run: ./run-em.sh
      - run: cd gauge-tests && npm install @getgauge/cli taiko && headless_chrome=true npx gauge run specs
      - run: ./shut-em-down.sh # is this needed or will the build service clean up the entire VM?

  cuke-tests:
    name: cuke tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd backend && cargo build
      - run: ./run-em-for-cukes.sh
      - run: cargo test --test cucumber