# from https://github.com/actions-rs/example
on: 
  push:
    tags:
      - '*'

name: Release Build

jobs:
  release-backend-build:
    name: release-backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd backend && cargo build --release
      - uses: appleboy/scp-action@master
        with:
          host: 54.212.63.158
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          source: "target/release/backend"
          target: "."
      - uses: appleboy/ssh-action@master
        with:
          host: 54.212.63.158
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          script: |
            sudo mv /app/backend /app/backend_old
            sudo cp ./target/release/backend /app/backend
            sudo systemctl restart rrmeals
  release-frontend-build:
    name: release-frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: echo "https://rampage.screaming3d.com" > frontend/src/api_loc.txt
      - run: cat frontend/src/api_loc.txt
      - run: cd frontend && cargo build --release && npx wasm-pack build --target web --out-name package
      - uses: appleboy/scp-action@master
        with:
          host: 54.212.63.158
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          source: "frontend/pkg/*,frontend/index.html"
          target: "frontend"
      - uses: appleboy/ssh-action@master
        with:
          host: 54.212.63.158
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          script: |
            sudo cp -rv ./frontend/frontend/* /var/www/html/
