# from https://github.com/actions-rs/example
on: 
  push:
    tags:
      - '*'

name: Release Build

jobs:
  release-backend-build:
    name: release-backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: echo ${{ secrets.DEPLOYSSH }} > ~/.ssh/id_rsa
      - run: echo ${{ secrets.DEPLOYSSHPW }} | ssh-add -p keyfile
      - run: cd backend && cargo build --release
      - run: ls
      - run: pwd
      - run: scp -v target/release/backend ubuntu:34.220.223.217:~/
      - run: echo  "run deploy script on destination"
  release-frontend-build:
    name: release-frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd frontend && cargo build --release && npx wasm-pack build --target web --out-name package
      - run: echo "Would have deployed frontend"
