# from https://github.com/actions-rs/example
on: 
  push:
    tags:
      - '*'

name: Release Build

jobs:
  release-backend-build:
    name: release-backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd backend && cargo build --release
      - run: ls
      - run: pwd 
      - uses: appleboy/scp-action@master
        with:
          host: 34.220.223.217
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          source: "target/release/backend"
          target: "."
      - uses: appleboy/ssh-action@master
        with:
          host: 34.220.223.217
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          script: |
            pwd
            ls
            sudo mv /app/backend /app/backend_old
            sudo cp ./target/release/backend /app/backend
            sudo systemctl restart rrmeals
  release-frontend-build:
    name: release-frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd frontend && cargo build --release && npx wasm-pack build --target web --out-name package
      - uses: appleboy/scp-action@master
        with:
          host: 34.220.223.217
          username: ubuntu
          key: ${{ secrets.DEPLOYSSH }}
          passphrase: ${{ secrets.DEPLOYSSHPW }}
          port: 22
          source: "frontend/pkg/*,frontend/index.html"
          target: "frontend"
